name: Atualizar idade

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite (UTC)
  workflow_dispatch: # Permite executar manualmente também

jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Calcular nova idade e atualizar README
        run: |
          #!/bin/bash
          DATA_NASC="1996-07-25"
          HOJE=$(date +%Y-%m-%d)
          IDADE=$(($(date -d "$HOJE" +%Y) - $(date -d "$DATA_NASC" +%Y)))
          if [[ "$(date -d "$HOJE" +%m%d)" -lt "0725" ]]; then
            IDADE=$((IDADE - 1))
          fi

          sed -i "s/<!-- idade -->.*<!-- \/idade -->/<!-- idade -->$IDADE<!-- \/idade -->/" README.md

      - name: Commit e push se houver alterações
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Atualiza idade automaticamente" || exit 0
          git push
